name: Boot Configuration Tampering Via Bcdedit.EXE
id: 1444443e-6757-43e4-9ea4-c8fc705f79a2
author: E.M. Anhaus (originally from Atomic Blue Detections, Endgame), oscd.community
date: 2019/10/24
level: high
description: Detects the use of the bcdedit command to tamper with the boot configuration
  data. This technique is often times used by malware or attackers as a destructive
  way before launching ransomware.
status: stable
modified: 2023/02/15
logsource:
  category: process_creation
  product: windows
tactics:
- impact
relevantTechniques:
- t1490
query: 'DeviceProcessEvents

  | where ((ProcessCommandLine contains "bootstatuspolicy" and ProcessCommandLine
  contains "ignoreallfailures") or (ProcessCommandLine contains "recoveryenabled"
  and ProcessCommandLine contains "no")) and (FolderPath endswith "\\bcdedit.exe"
  or ProcessVersionInfoOriginalFileName =~ "bcdedit.exe") and ProcessCommandLine contains
  "set"'
