name: CLR DLL Loaded Via Office Applications
id: d13c43f0-f66b-4279-8b2c-5912077c1780
author: Antonlovesdnb
date: 2020/02/19
level: medium
description: Detects CLR DLL being loaded by an Office Product
status: test
modified: 2023/03/29
logsource:
  category: image_load
  product: windows
tactics:
- execution
relevantTechniques:
- t1204.002
query: 'DeviceImageLoadEvents

  | where FolderPath contains "\\clr.dll" and (InitiatingProcessFolderPath endswith
  "\\excel.exe" or InitiatingProcessFolderPath endswith "\\mspub.exe" or InitiatingProcessFolderPath
  endswith "\\outlook.exe" or InitiatingProcessFolderPath endswith "\\onenote.exe"
  or InitiatingProcessFolderPath endswith "\\onenoteim.exe" or InitiatingProcessFolderPath
  endswith "\\powerpnt.exe" or InitiatingProcessFolderPath endswith "\\winword.exe")'
