name: DeviceCredentialDeployment Execution
id: b8b1b304-a60f-4999-9a6e-c547bde03ffd
author: Nasreddine Bencherchali (Nextron Systems)
date: 2022/08/19
level: medium
description: Detects the execution of DeviceCredentialDeployment to hide a process
  from view
status: test
modified: ''
logsource:
  category: process_creation
  product: windows
tactics:
- defense_evasion
relevantTechniques:
- t1218
query: 'DeviceProcessEvents

  | where FolderPath endswith "\\DeviceCredentialDeployment.exe"'
