name: DotNET Assembly DLL Loaded Via Office Application
id: ff0f2b05-09db-4095-b96d-1b75ca24894a
author: Antonlovesdnb
date: 2020/02/19
level: medium
description: Detects any assembly DLL being loaded by an Office Product
status: test
modified: 2023/03/29
logsource:
  category: image_load
  product: windows
tactics:
- execution
relevantTechniques:
- t1204.002
query: 'DeviceImageLoadEvents

  | where FolderPath startswith "C:\\Windows\\assembly\\" and (InitiatingProcessFolderPath
  endswith "\\excel.exe" or InitiatingProcessFolderPath endswith "\\mspub.exe" or
  InitiatingProcessFolderPath endswith "\\onenote.exe" or InitiatingProcessFolderPath
  endswith "\\onenoteim.exe" or InitiatingProcessFolderPath endswith "\\outlook.exe"
  or InitiatingProcessFolderPath endswith "\\powerpnt.exe" or InitiatingProcessFolderPath
  endswith "\\winword.exe")'
