name: PowerShell Core DLL Loaded Via Office Application
id: bb2ba6fb-95d4-4a25-89fc-30bb736c021a
author: Nasreddine Bencherchali (Nextron Systems)
date: 2023/06/01
level: medium
description: Detects PowerShell core DLL being loaded by an Office Product
status: test
modified: ''
logsource:
  category: image_load
  product: windows
tactics:
- defense_evasion
relevantTechniques: []
query: 'DeviceImageLoadEvents

  | where (FolderPath contains "\\System.Management.Automation.Dll" or FolderPath
  contains "\\System.Management.Automation.ni.Dll") and (InitiatingProcessFolderPath
  endswith "\\excel.exe" or InitiatingProcessFolderPath endswith "\\mspub.exe" or
  InitiatingProcessFolderPath endswith "\\outlook.exe" or InitiatingProcessFolderPath
  endswith "\\onenote.exe" or InitiatingProcessFolderPath endswith "\\onenoteim.exe"
  or InitiatingProcessFolderPath endswith "\\powerpnt.exe" or InitiatingProcessFolderPath
  endswith "\\winword.exe")'
