name: Sysmon Configuration Update
id: 87911521-7098-470b-a459-9a57fc80bdfd
author: Nasreddine Bencherchali (Nextron Systems)
date: 2023/03/09
level: medium
description: Detects updates to Sysmon's configuration. Attackers might update or
  replace the Sysmon configuration with a bare bone one to avoid monitoring without
  shutting down the service completely
status: test
modified: 2024/03/13
logsource:
  category: process_creation
  product: windows
tactics:
- defense_evasion
relevantTechniques:
- t1562.001
query: 'DeviceProcessEvents

  | where (ProcessCommandLine contains "-c" or ProcessCommandLine contains "/c") and
  ((FolderPath endswith "\\Sysmon64.exe" or FolderPath endswith "\\Sysmon.exe") or
  ProcessVersionInfoFileDescription =~ "System activity monitor")'
